In [ ]:
import pandas as pd

df = pd.read_csv("../data/processed/cleaned_reviews.csv")

print(df.shape)
df.head()

In [1]:
import pandas as pd

test_df = pd.read_csv(
    "../data/processed/cleaned_reviews.csv",
    nrows=5
)

print(test_df.shape)
test_df

(5, 9)

,Product_name,Price,Rate,Review,Summary,full_review,sentiment,review_length,word_count
0,"Crompton 75 L Desert Air Cooler(White, Teal, A...","??10,499",5.0,Simply awesome,it's really worth every single penny. it works...,Simply awesome it's really worth every single ...,Positive,508,92
1,"Crompton 75 L Desert Air Cooler(White, Teal, A...","??10,499",4.0,Worth the money . Desert Cooler live up to the...,I bought Crompton Ozone 75 Desert Air Cooler i...,Worth the money . Desert Cooler live up to the...,Positive,548,112
2,"Crompton 75 L Desert Air Cooler(White, Teal, A...","??10,499",5.0,Worth every penny,GREAT packaging by seller. As this was the mos...,Worth every penny GREAT packaging by seller. A...,Positive,518,89
3,"Crompton 75 L Desert Air Cooler(White, Teal, A...","??10,499",5.0,Fabulous!,Delivery was delayed by two days except this e...,Fabulous! Delivery was delayed by two days exc...,Positive,414,69
4,"Crompton 75 L Desert Air Cooler(White, Teal, A...","??10,499",4.0,Nice product,A Good cooler by Crompton. The height of the c...,Nice product A Good cooler by Crompton. The he...,Positive,515,102

In [2]:
df = pd.read_csv(
    "../data/processed/cleaned_reviews.csv",
    encoding="utf-8"
)

print("Loaded successfully")
print(df.shape)

Loaded successfully
(306316, 9)

In [3]:
import re
import nltk

from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

In [4]:
lemmatizer = WordNetLemmatizer()

stop_words = set(stopwords.words("english"))

stop_words = stop_words - {"no", "not", "nor"}

In [5]:
def preprocess_text(text):
    text = text.lower()

    text = re.sub(r"[^a-zA-Z\s]", " ", text)

    text = re.sub(r"\s+", " ", text).strip()

    tokens = word_tokenize(text)

    tokens = [
        word for word in tokens
        if word not in stop_words
    ]

    tokens = [
        lemmatizer.lemmatize(word)
        for word in tokens
    ]

    return " ".join(tokens)

In [6]:
print(df["full_review"].iloc[0])

print("\nAfter preprocessing:")

print(preprocess_text(df["full_review"].iloc[0]))

Simply awesome it's really worth every single penny. it works like one ton AC provided that your room has proper ventilation.  I generally keep cooler near to window so that it can pull fresh air from outside and as a result I get very cool air. one more suggestion,  please don't buy cooler which are equipped with a blower fan. Always go for the cooler equipped with metal fan like this one.  In one word, this Compton cooler is Amazing. if you find the review helpful, please thumps up. Happy summer! ????

After preprocessing:
simply awesome really worth every single penny work like one ton ac provided room proper ventilation generally keep cooler near window pull fresh air outside result get cool air one suggestion please buy cooler equipped blower fan always go cooler equipped metal fan like one one word compton cooler amazing find review helpful please thump happy summer

In [7]:
df["clean_text"] = df["full_review"].apply(preprocess_text)

In [8]:
print(df.shape)
print(df.columns.tolist())

(306316, 10)
['Product_name', 'Price', 'Rate', 'Review', 'Summary', 'full_review', 'sentiment', 'review_length', 'word_count', 'clean_text']

In [9]:
df.to_csv(
    "../data/processed/nlp_processed_reviews.csv",
    index=False
)

In [10]:
import os

print(
    os.path.exists(
        "../data/processed/nlp_processed_reviews.csv"
    )
)

True

In [11]:
y = df["sentiment"]

print(y.head())

0    Positive
1    Positive
2    Positive
3    Positive
4    Positive
Name: sentiment, dtype: str

In [12]:
print(y.shape)

(306316,)

In [13]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [14]:
tfidf = TfidfVectorizer(
    max_features=5000,
    ngram_range=(1, 2),
    min_df=5,
    max_df=0.90
)

In [15]:
X = tfidf.fit_transform(df["clean_text"])

In [16]:
print(X.shape)

(306316, 5000)

In [17]:
y = df["sentiment"]

X = tfidf.fit_transform(df["clean_text"])

print("X:", X.shape)
print("y:", y.shape)

X: (306316, 5000)
y: (306316,)

In [18]:
from sklearn.model_selection import train_test_split

In [19]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

In [20]:
print("X_train:", X_train.shape)
print("X_test :", X_test.shape)

print("y_train:", y_train.shape)
print("y_test :", y_test.shape)

X_train: (245052, 5000)
X_test : (61264, 5000)
y_train: (245052,)
y_test : (61264,)

In [21]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(
    max_iter=1000
)

In [22]:
model.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

In [23]:
print(model.classes_)

['Negative' 'Neutral' 'Positive']

In [24]:
prediction = model.predict(X_test[0])

print(prediction)

['Positive']

In [25]:
print("Predicted:", model.predict(X_test[0])[0])
print("Actual   :", y_test.iloc[0])

Predicted: Positive
Actual   : Positive

In [26]:
index = y_test.index[0]

print("REVIEW:")
print(df.loc[index, "full_review"])

print("\nACTUAL:")
print(y_test.iloc[0])

print("\nPREDICTED:")
print(model.predict(X_test[0])[0])

REVIEW:
Just wow! It's amazing

ACTUAL:
Positive

PREDICTED:
Positive

In [27]:
probabilities = model.predict_proba(X_test[0])[0]

for sentiment, probability in zip(model.classes_, probabilities):
    print(sentiment, ":", round(probability * 100, 2), "%")

Negative : 0.05 %
Neutral : 0.16 %
Positive : 99.79 %

In [28]:
y_pred = model.predict(X_test)

In [29]:
print(y_pred.shape)

(61264,)

In [30]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

Accuracy: 0.9819796291459911

In [31]:
print("Accuracy:", round(accuracy * 100, 2), "%")

Accuracy: 98.2 %

In [32]:
from sklearn.metrics import classification_report

print(
    classification_report(
        y_test,
        y_pred
    )
)

              precision    recall  f1-score   support

    Negative       0.99      0.99      0.99      9924
     Neutral       0.95      0.87      0.91      5570
    Positive       0.98      0.99      0.99     45770

    accuracy                           0.98     61264
   macro avg       0.97      0.95      0.96     61264
weighted avg       0.98      0.98      0.98     61264

In [33]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

    Negative       0.99      0.99      0.99      9924
     Neutral       0.95      0.87      0.91      5570
    Positive       0.98      0.99      0.99     45770

    accuracy                           0.98     61264
   macro avg       0.97      0.95      0.96     61264
weighted avg       0.98      0.98      0.98     61264

In [34]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(
    y_test,
    y_pred,
    labels=model.classes_
)

print(model.classes_)
print(cm)

['Negative' 'Neutral' 'Positive']
[[ 9801    37    86]
 [   68  4870   632]
 [   51   230 45489]]

In [35]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(
    y_test,
    y_pred,
    labels=model.classes_
)

print(model.classes_)
print(cm)

['Negative' 'Neutral' 'Positive']
[[ 9801    37    86]
 [   68  4870   632]
 [   51   230 45489]]

In [36]:
X_text = df["clean_text"]
y = df["sentiment"]

In [37]:
from sklearn.model_selection import train_test_split

X_train_text, X_test_text, y_train, y_test = train_test_split(
    X_text,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

In [38]:
print("Training text:", X_train_text.shape)
print("Testing text :", X_test_text.shape)

Training text: (245052,)
Testing text : (61264,)

In [39]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf_final = TfidfVectorizer(
    max_features=5000,
    ngram_range=(1, 2),
    min_df=5,
    max_df=0.90
)

In [40]:
X_train = tfidf_final.fit_transform(X_train_text)

In [41]:
X_test = tfidf_final.transform(X_test_text)

In [42]:
print("X_train:", X_train.shape)
print("X_test :", X_test.shape)

X_train: (245052, 5000)
X_test : (61264, 5000)

In [43]:
from sklearn.linear_model import LogisticRegression

final_model = LogisticRegression(
    max_iter=1000
)

final_model.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

In [44]:
y_pred = final_model.predict(X_test)

In [45]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)

print(
    "Final Accuracy:",
    round(accuracy * 100, 2),
    "%"
)

Final Accuracy: 98.19 %

In [46]:
from sklearn.metrics import classification_report

print(
    classification_report(
        y_test,
        y_pred
    )
)

              precision    recall  f1-score   support

    Negative       0.99      0.99      0.99      9924
     Neutral       0.95      0.88      0.91      5570
    Positive       0.98      0.99      0.99     45770

    accuracy                           0.98     61264
   macro avg       0.97      0.95      0.96     61264
weighted avg       0.98      0.98      0.98     61264

In [47]:
def predict_sentiment(review):

    cleaned = preprocess_text(review)

    vector = tfidf_final.transform([cleaned])

    prediction = final_model.predict(vector)[0]

    probabilities = final_model.predict_proba(vector)[0]

    return prediction, probabilities

In [48]:
review = "This product is absolutely terrible. Waste of money and stopped working."

prediction, probabilities = predict_sentiment(review)

print("Prediction:", prediction)

for sentiment, probability in zip(final_model.classes_, probabilities):
    print(
        sentiment,
        ":",
        round(probability * 100, 2),
        "%"
    )

Prediction: Negative
Negative : 99.88 %
Neutral : 0.06 %
Positive : 0.06 %

In [49]:
review = "Amazing product. Excellent quality and totally worth the money."

prediction, probabilities = predict_sentiment(review)

print("Prediction:", prediction)

for sentiment, probability in zip(final_model.classes_, probabilities):
    print(sentiment, ":", round(probability * 100, 2), "%")

Prediction: Positive
Negative : 0.05 %
Neutral : 0.09 %
Positive : 99.86 %

In [50]:
review = "The product is okay. Nothing special but it works."

prediction, probabilities = predict_sentiment(review)

print("Prediction:", prediction)

for sentiment, probability in zip(final_model.classes_, probabilities):
    print(sentiment, ":", round(probability * 100, 2), "%")

Prediction: Neutral
Negative : 6.35 %
Neutral : 61.7 %
Positive : 31.96 %

In [51]:
import os

os.makedirs("../models", exist_ok=True)

In [52]:
import joblib

In [53]:
joblib.dump(
    final_model,
    "../models/sentiment_model.pkl"
)

['../models/sentiment_model.pkl']

In [54]:
joblib.dump(
    tfidf_final,
    "../models/tfidf_vectorizer.pkl"
)

['../models/tfidf_vectorizer.pkl']

In [55]:
print(
    os.path.exists(
        "../models/sentiment_model.pkl"
    )
)

print(
    os.path.exists(
        "../models/tfidf_vectorizer.pkl"
    )
)

True
True

In [56]:
loaded_model = joblib.load(
    "../models/sentiment_model.pkl"
)

loaded_tfidf = joblib.load(
    "../models/tfidf_vectorizer.pkl"
)

In [57]:
print(loaded_model.classes_)

['Negative' 'Neutral' 'Positive']

In [1]:
import numpy as np

A = np.array([2, 2])
B = np.array([4, 4])

dot_product = np.dot(A, B)

magnitude_A = np.linalg.norm(A)
magnitude_B = np.linalg.norm(B)

cosine_similarity = dot_product / (
    magnitude_A * magnitude_B
)

print(cosine_similarity)

0.9999999999999998

In [2]:
A = np.array([2, 2])
C = np.array([-2, -2])

cosine_similarity = np.dot(A, C) / (
    np.linalg.norm(A) * np.linalg.norm(C)
)

print(cosine_similarity)

-0.9999999999999998

In [3]:
from sentence_transformers import SentenceTransformer

c:\Users\RUSHIKESH\Desktop\customer-review-intelligence\venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [4]:
embedding_model = SentenceTransformer(
    "sentence-transformers/all-MiniLM-L6-v2"
)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
c:\Users\RUSHIKESH\Desktop\customer-review-intelligence\venv\Lib\site-packages\huggingface_hub\file_download.py:141: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\RUSHIKESH\.cache\huggingface\hub\models--sentence-transformers--all-MiniLM-L6-v2. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 6789.25it/s]

In [5]:
sentence = "Battery drains very quickly."

In [6]:
embedding = embedding_model.encode(sentence)

In [7]:
embedding

array([ 4.23443802e-02,  6.84453771e-02,  4.07577083e-02,  2.05847397e-02,
        2.24376526e-02, -4.76915054e-02, -2.66008545e-02,  2.18102392e-02,
        1.00337379e-01,  5.70784546e-02, -1.96329765e-02,  6.01917505e-02,
       -3.63771170e-02,  1.01048991e-01,  1.37857655e-02,  1.65194701e-02,
        1.61430258e-02, -2.51111817e-02, -2.82504074e-02, -5.43586984e-02,
        6.43687323e-02, -7.22889975e-02,  3.80654968e-02,  3.37671442e-03,
        6.25481829e-02,  3.40962633e-02,  1.15452548e-02, -2.06394680e-02,
       -3.13156843e-02, -5.83341792e-02, -8.76207128e-02,  6.41768128e-02,
        7.47050298e-03, -1.80540625e-02,  4.22609448e-02,  4.73440513e-02,
       -7.92872831e-02,  9.30086747e-02,  4.73331921e-02, -6.83159754e-02,
       -7.01188575e-03,  3.78395617e-02,  1.04748763e-01, -2.38667578e-02,
        3.87798622e-02,  3.90970223e-02, -6.17843401e-03, -1.50071252e-02,
        9.02467072e-02, -4.14711051e-03,  7.53359050e-02,  1.21283280e-02,
       -1.16332783e-03, -6.59416709e-03, -5.98086454e-02, -4.68277186e-02,
        3.51113752e-02, -5.97842969e-02,  1.62528548e-02, -3.71994562e-02,
       -8.87673274e-02, -1.35324989e-02, -7.20172888e-04,  5.43926097e-02,
       -7.24475691e-03, -1.01398071e-03,  1.44969346e-02, -5.69995493e-03,
       -2.92524211e-02,  3.71842347e-02, -3.38012502e-02,  8.33811536e-02,
       -3.54384109e-02, -6.32851198e-02, -5.53409979e-02, -4.60486375e-02,
        7.37370178e-02,  3.05632129e-02,  2.63804961e-02, -2.43691169e-02,
        1.75515395e-02, -3.61008383e-02, -2.04551145e-02,  7.23855793e-02,
        1.25270262e-01, -9.00161453e-03,  7.45165572e-02, -5.75027503e-02,
       -1.28013134e-01, -1.89597979e-02, -4.71695624e-02,  7.42621645e-02,
        6.87979087e-02,  1.13094207e-02, -5.61547577e-02, -8.00066814e-03,
        8.18280503e-02, -8.07859283e-03, -7.60699958e-02,  6.18774109e-02,
        3.83697674e-02,  6.92520365e-02,  4.41374294e-02,  2.75741555e-02,
       -4.56340471e-03, -1.78208910e-02,  2.23446637e-02,  9.65509489e-02,
       -1.59295723e-02,  8.89399648e-03,  4.91797216e-02, -1.20396428e-02,
        1.09519428e-02,  1.15441449e-01,  3.02710780e-03,  5.41821420e-02,
       -6.00603372e-02,  4.64600138e-02, -2.79462594e-03,  7.42729455e-02,
       -2.07062066e-02,  2.95082331e-02, -4.76797521e-02, -6.71076253e-02,
        1.99016556e-02,  4.85292748e-02,  4.31659929e-02, -1.97135252e-33,
       -2.96632275e-02, -4.52390835e-02,  1.12488139e-02, -1.14119081e-02,
       -9.83207822e-02, -2.78330743e-02, -6.16808012e-02,  2.46529821e-02,
        9.72793438e-03,  1.16238780e-02, -4.68892865e-02, -3.52112502e-02,
       -6.05393798e-05, -2.12544925e-03,  3.74591025e-03, -1.08864501e-01,
       -1.94151956e-03, -1.62812916e-03,  1.87752023e-02, -6.37770891e-02,
        2.58853622e-02, -7.44762048e-02, -9.02231038e-03,  2.13701297e-02,
        1.11687183e-01, -2.03493126e-02,  7.81170875e-02, -4.43498641e-02,
       -8.57155584e-03,  2.90133804e-02,  1.28572723e-02,  1.38443615e-02,
       -1.42650725e-02, -7.24072382e-02,  5.45630753e-02,  1.83520820e-02,
        8.12253654e-02,  1.79258063e-02,  3.04112025e-02, -5.70099466e-02,
       -8.75067040e-02,  4.43250574e-02, -7.82014951e-02, -1.02282753e-02,
       -1.89841222e-02, -7.68174082e-02, -5.67418225e-02,  1.51027180e-02,
       -3.42911221e-02,  7.87718743e-02, -4.18912619e-02, -1.07526742e-02,
       -4.27817255e-02,  7.05119073e-02, -3.82793173e-02,  4.55506854e-02,
        7.21696988e-02, -4.49685156e-02,  3.20316181e-02,  1.01180904e-01,
        3.27818207e-02,  1.02438480e-01, -6.87892959e-02, -3.99094187e-02,
       -4.38765716e-03, -1.51069611e-02,  2.47346312e-02,  6.03950545e-02,
       -3.27287056e-02, -7.16288434e-03,  1.44204022e-02, -6.73098713e-02,
        8.55471864e-02, -8.11720490e-02, -6.29121140e-02,  2.98033152e-02,
       -2.68145557e-02, -6.28046021e-02, -9.81576592e-02, -5.56824431e-02,
       -3.46189328e-02, -6.03354312e-02,  5.00335842e-02, -8.35869163e-02,
        2.00527553e-02, -6.84537515e-02,  7.47674471e-03, -8.53397623e-02,
       -3.27771157e-02,  1.12201143e-02,  3.25247413e-03,  3.73475067e-02,
        4.80329012e-03, -4.86763455e-02, -2.12762076e-02,  2.20082646e-33,
       -4.88927215e-03, -6.43320233e-02,  6.20529614e-02,  2.00353041e-02,
        4.54863682e-02,  1.85494125e-02, -8.70848745e-02,  6.70497939e-02,
       -9.38752666e-02,  3.81208882e-02, -3.43130119e-02,  4.22330350e-02,
       -1.30694002e-01, -2.79884916e-02,  1.54420048e-01,  4.84768599e-02,
        8.87045935e-02, -4.60055694e-02,  5.77015243e-02,  3.20346132e-02,
        3.39083374e-02,  1.20365813e-01, -2.65092589e-02,  2.86356211e-02,
       -4.05058004e-02,  3.40705179e-02, -5.92594640e-03,  5.22922836e-02,
       -1.66594330e-02,  6.78292569e-03, -2.95645604e-03,  1.95529852e-02,
       -7.00397864e-02,  2.06275713e-02, -2.86474042e-02, -9.39810369e-03,
       -1.38657866e-02,  1.74433924e-02, -1.00510661e-02, -2.88557466e-02,
        3.23578790e-02, -1.89737394e-03,  4.78537614e-03, -2.83376556e-02,
       -4.09102067e-03, -2.34015118e-02, -6.95835873e-02, -2.14592200e-02,
       -1.73606575e-02,  1.08398966e-01,  2.61760242e-02, -7.71255940e-02,
       -1.00490870e-02,  7.45565146e-02,  8.26647691e-03, -6.79507554e-02,
        2.41585448e-02,  6.44703768e-03, -4.61259112e-02, -3.49690802e-02,
        9.55950245e-02,  3.78533974e-02, -5.32289594e-02, -6.89829215e-02,
        1.91636160e-02, -4.35038209e-02,  1.21815562e-01,  2.04473343e-02,
        8.95769596e-02, -2.64944173e-02, -2.85406020e-02,  3.56011316e-02,
        2.35450938e-02, -5.46437390e-02, -5.49449101e-02, -1.26950722e-02,
       -4.96193282e-02,  1.82067975e-02, -4.30634357e-02, -7.22203031e-02,
        5.38765378e-02,  8.99869483e-03,  1.58167258e-02, -1.08666316e-01,
       -4.72836681e-02, -9.99828652e-02, -1.21380370e-02, -4.01267000e-02,
        2.61496641e-02,  4.99272421e-02,  5.85209280e-02, -3.11546009e-02,
       -7.55309090e-02,  6.32862747e-02, -9.38066989e-02, -1.48871422e-08,
        1.44450059e-02,  1.27175571e-02,  1.19105048e-01,  5.97655922e-02,
       -1.01898203e-03, -7.04913214e-02,  8.26219097e-02,  1.50822192e-01,
        9.27613955e-03, -6.21892475e-02,  8.75912905e-02, -2.04031672e-02,
        2.37623099e-02,  1.30254412e-02,  5.97307757e-02,  4.35383357e-02,
       -2.68816669e-02,  1.06823882e-02, -2.50013601e-02, -6.03367388e-03,
       -7.62552768e-02,  1.11042650e-03, -6.49132878e-02, -1.14847142e-02,
        1.95195414e-02,  8.42768885e-03, -1.82817876e-02, -2.90187635e-02,
        5.44127896e-02, -6.60832375e-02, -5.87053634e-02,  5.19456342e-02,
       -4.40398902e-02, -3.75251868e-03,  6.10716315e-03, -2.07066163e-02,
        5.42678684e-02, -9.00572389e-02,  1.64186340e-02,  5.98475374e-02,
        4.22962941e-03, -3.87285999e-03, -5.14461324e-02, -1.73436850e-02,
        4.52822400e-03, -5.35492878e-03,  3.37149948e-02,  1.03907734e-02,
        2.11196356e-02,  7.37998262e-02, -1.56046562e-02, -5.46430191e-03,
       -3.16639543e-02, -6.28967397e-03,  2.48437934e-02,  1.22117123e-03,
       -8.52421764e-03, -1.03005674e-02,  1.42391231e-02,  1.90943072e-03,
        6.85304478e-02, -6.33055270e-02,  3.35483588e-02, -5.04813576e-03],
      dtype=float32)

In [8]:
print(embedding.shape)

(384,)

In [9]:
print(embedding[:10])

[ 0.04234438  0.06844538  0.04075771  0.02058474  0.02243765 -0.04769151
 -0.02660085  0.02181024  0.10033738  0.05707845]

In [10]:
sentences = [
    "Battery drains very quickly.",
    "The phone does not hold charge for long.",
    "The camera takes beautiful photos."
]

embeddings = embedding_model.encode(sentences)

In [11]:
print(embeddings.shape)

(3, 384)

In [12]:
A = embeddings[0]
B = embeddings[1]
C = embeddings[2]

In [13]:
from sklearn.metrics.pairwise import cosine_similarity

In [14]:
similarity_AB = cosine_similarity([A], [B])[0][0]

print(similarity_AB)

0.35002488

In [15]:
similarity_AC = cosine_similarity([A], [C])[0][0]

print(similarity_AC)

0.11947813

In [16]:
print(
    "Battery vs Charge:",
    round(similarity_AB, 4)
)

print(
    "Battery vs Camera:",
    round(similarity_AC, 4)
)

Battery vs Charge: 0.35
Battery vs Camera: 0.1195

In [17]:
import chromadb

In [18]:
client = chromadb.Client()

In [19]:
collection = client.create_collection(
    name="demo_reviews"
)

In [20]:
reviews = [
    "Battery drains very quickly.",
    "The phone needs charging several times a day.",
    "Camera quality is excellent.",
    "The delivery arrived very late.",
    "Battery backup became poor after the update.",
    "The display is bright and beautiful."
]

In [25]:
ids = [
    "review_1",
    "review_2",
    "review_3",
    "review_4",
    "review_5",
    "review_6"
]

print(ids)

['review_1', 'review_2', 'review_3', 'review_4', 'review_5', 'review_6']

In [21]:
review_embeddings = embedding_model.encode(
    reviews
)

In [26]:
print(len(reviews))
print(len(review_embeddings_list))
print(len(metadatas))
print(len(ids))

6

NameError: name 'review_embeddings_list' is not defined

In [22]:
print(review_embeddings.shape)

(6, 384)

In [23]:
metadatas = [
    {"topic": "battery"},
    {"topic": "battery"},
    {"topic": "camera"},
    {"topic": "delivery"},
    {"topic": "battery"},
    {"topic": "display"}
]

In [24]:
collection.add(
    ids=ids,
    documents=reviews,
    embeddings=review_embeddings_list,
    metadatas=metadatas
)

NameError: name 'ids' is not defined

In [27]:
print(embedding_model)

SentenceTransformer(
  (0): Transformer({'transformer_task': 'feature-extraction', 'modality_config': {'text': {'method': 'forward', 'method_output_name': 'last_hidden_state'}}, 'module_output_name': 'token_embeddings', 'architecture': 'BertModel'})
  (1): Pooling({'embedding_dimension': 384, 'pooling_mode': 'mean', 'include_prompt': True})
  (2): Normalize({})
)

In [28]:
review_embeddings_list = review_embeddings.tolist()

In [29]:
print(len(review_embeddings_list))
print(len(review_embeddings_list[0]))

6
384

In [30]:
ids = [
    "review_1",
    "review_2",
    "review_3",
    "review_4",
    "review_5",
    "review_6"
]

metadatas = [
    {"topic": "battery"},
    {"topic": "battery"},
    {"topic": "camera"},
    {"topic": "delivery"},
    {"topic": "battery"},
    {"topic": "display"}
]

In [31]:
print("Reviews:", len(reviews))
print("Embeddings:", len(review_embeddings_list))
print("Metadata:", len(metadatas))
print("IDs:", len(ids))

Reviews: 6
Embeddings: 6
Metadata: 6
IDs: 6

In [32]:
collection.add(
    ids=ids,
    documents=reviews,
    embeddings=review_embeddings_list,
    metadatas=metadatas
)

print("Records stored:", collection.count())

Records stored: 6

In [33]:
query = "What problems are users having with charging?"

In [34]:
query_embedding = embedding_model.encode(query)

print(query_embedding.shape)

(384,)

In [35]:
results = collection.query(
    query_embeddings=[query_embedding.tolist()],
    n_results=3
)

In [36]:
print(results["documents"][0])

['The phone needs charging several times a day.', 'Battery drains very quickly.', 'Battery backup became poor after the update.']

In [37]:
documents = results["documents"][0]
distances = results["distances"][0]

for i, (document, distance) in enumerate(
    zip(documents, distances),
    start=1
):
    print(f"Result {i}")
    print("Review:", document)
    print("Distance:", round(distance, 4))
    print()

Result 1
Review: The phone needs charging several times a day.
Distance: 1.0629

Result 2
Review: Battery drains very quickly.
Distance: 1.2613

Result 3
Review: Battery backup became poor after the update.
Distance: 1.4576

In [38]:
query = "How is the picture and camera quality?"

query_embedding = embedding_model.encode(query)

results = collection.query(
    query_embeddings=[query_embedding.tolist()],
    n_results=3
)

documents = results["documents"][0]
distances = results["distances"][0]

for i, (document, distance) in enumerate(
    zip(documents, distances),
    start=1
):
    print(f"Result {i}")
    print("Review:", document)
    print("Distance:", round(distance, 4))
    print()

Result 1
Review: Camera quality is excellent.
Distance: 0.407

Result 2
Review: The display is bright and beautiful.
Distance: 1.3061

Result 3
Review: Battery drains very quickly.
Distance: 1.7309

In [39]:
print(df.shape)

NameError: name 'df' is not defined

In [40]:
import pandas as pd

df = pd.read_csv("../data/processed/nlp_processed_reviews.csv")

In [41]:
print(df.shape)
print(df.columns)

(306316, 10)
Index(['Product_name', 'Price', 'Rate', 'Review', 'Summary', 'full_review',
       'sentiment', 'review_length', 'word_count', 'clean_text'],
      dtype='str')

In [42]:
df[["Product_name", "Rate", "full_review", "sentiment"]].isnull().sum()

Product_name    0
Rate            0
full_review     0
sentiment       0
dtype: int64

In [43]:
rag_df = df[
    ["Product_name", "Rate", "full_review", "sentiment"]
].sample(
    n=1000,
    random_state=42
).reset_index(drop=True)

print(rag_df.shape)

(1000, 4)

In [44]:
rag_df.head(3)

,Product_name,Rate,full_review,sentiment
0,PHILIPS MMS8085B/94 Convertible 80 W Bluetooth...,4.0,Good quality product a good quality product fr...,Positive
1,Crompton 88 L Desert Air Cooler with Honeycomb...,4.0,Good quality product Ok,Positive
2,Cosito 144 TC Cotton Double Floral Flat Bedshe...,5.0,Mind-blowing purchase The product is very nice...,Positive

In [45]:
documents = rag_df["full_review"].tolist()

print("Number of documents:", len(documents))
print()
print("First document:")
print(documents[0])

Number of documents: 1000

First document:
Good quality product a good quality product from philips.unexpectable bass..awsome..

In [46]:
real_embeddings = embedding_model.encode(
    documents,
    show_progress_bar=True
)

print(real_embeddings.shape)

Batches: 100%|██████████| 32/32 [00:05<00:00,  5.37it/s]

(1000, 384)

In [47]:
real_ids = [
    f"real_review_{i}"
    for i in range(len(rag_df))
]

print("Number of IDs:", len(real_ids))
print("First 5 IDs:", real_ids[:5])

Number of IDs: 1000
First 5 IDs: ['real_review_0', 'real_review_1', 'real_review_2', 'real_review_3', 'real_review_4']

In [48]:
first_metadata = {
    "product": str(rag_df.loc[0, "Product_name"]),
    "rating": float(rag_df.loc[0, "Rate"]),
    "sentiment": str(rag_df.loc[0, "sentiment"])
}

print(first_metadata)

{'product': 'PHILIPS MMS8085B/94 Convertible 80 W Bluetooth Home Theatre(Black, 2.1 Channel)', 'rating': 4.0, 'sentiment': 'Positive'}

In [49]:
real_metadatas = []

for _, row in rag_df.iterrows():
    real_metadatas.append({
        "product": str(row["Product_name"]),
        "rating": float(row["Rate"]),
        "sentiment": str(row["sentiment"])
    })

print("Number of metadata records:", len(real_metadatas))
print()
print("First metadata:")
print(real_metadatas[0])

Number of metadata records: 1000

First metadata:
{'product': 'PHILIPS MMS8085B/94 Convertible 80 W Bluetooth Home Theatre(Black, 2.1 Channel)', 'rating': 4.0, 'sentiment': 'Positive'}

In [50]:
print("Documents :", len(documents))
print("Embeddings:", len(real_embeddings))
print("IDs       :", len(real_ids))
print("Metadata  :", len(real_metadatas))

Documents : 1000
Embeddings: 1000
IDs       : 1000
Metadata  : 1000

In [51]:
import chromadb

persistent_client = chromadb.PersistentClient(
    path="../vector_db"
)

In [52]:
print(persistent_client)

<chromadb.api.client.Client object at 0x0000026BD946A550>

In [53]:
real_collection = persistent_client.get_or_create_collection(
    name="customer_reviews"
)

print("Records currently stored:", real_collection.count())

Records currently stored: 0

In [54]:
real_collection.add(
    ids=real_ids,
    documents=documents,
    embeddings=real_embeddings.tolist(),
    metadatas=real_metadatas
)

In [55]:
print("Records stored:", real_collection.count())

Records stored: 1000

In [56]:
query = "Customers complaining about poor product quality"

query_embedding = embedding_model.encode(query)

print(query_embedding.shape)

(384,)

In [57]:
results = real_collection.query(
    query_embeddings=[query_embedding.tolist()],
    n_results=5
)

In [58]:
for i, review in enumerate(
    results["documents"][0],
    start=1
):
    print(f"Result {i}:")
    print(review)
    print()

Result 1:
Bad quality Bad quality product

Result 2:
Expected a better product Not good

Result 3:
Good quality product Low money good product

Result 4:
Unsatisfactory - Poor Product  + Poor Customer Service I have to purchase last month 16th Oct  and with in 1 month its showing error in system in this radio, i have to complaint but already 7 days gone, no one can give the exactly response.

Result 5:
Good quality product Quality is good.

In [59]:
for i, (review, metadata) in enumerate(
    zip(
        results["documents"][0],
        results["metadatas"][0]
    ),
    start=1
):
    print(f"Result {i}")
    print("Review:", review)
    print("Sentiment:", metadata["sentiment"])
    print()

Result 1
Review: Bad quality Bad quality product
Sentiment: Negative

Result 2
Review: Expected a better product Not good
Sentiment: Negative

Result 3
Review: Good quality product Low money good product
Sentiment: Positive

Result 4
Review: Unsatisfactory - Poor Product  + Poor Customer Service I have to purchase last month 16th Oct  and with in 1 month its showing error in system in this radio, i have to complaint but already 7 days gone, no one can give the exactly response.
Sentiment: Negative

Result 5
Review: Good quality product Quality is good.
Sentiment: Positive

In [60]:
negative_results = real_collection.query(
    query_embeddings=[query_embedding.tolist()],
    n_results=5,
    where={"sentiment": "Negative"}
)

In [61]:
for i, review in enumerate(
    negative_results["documents"][0],
    start=1
):
    print(f"Result {i}:")
    print(review)
    print()

Result 1:
Bad quality Bad quality product

Result 2:
Expected a better product Not good

Result 3:
Unsatisfactory - Poor Product  + Poor Customer Service I have to purchase last month 16th Oct  and with in 1 month its showing error in system in this radio, i have to complaint but already 7 days gone, no one can give the exactly response.

Result 4:
Horrible waste of money , quality is very bad

Result 5:
Did not meet expectations Worst qualityPlease don't buy

In [62]:
for i, (review, distance) in enumerate(
    zip(
        negative_results["documents"][0],
        negative_results["distances"][0]
    ),
    start=1
):
    print(f"Result {i}")
    print("Review:", review)
    print("Distance:", round(distance, 4))
    print()

Result 1
Review: Bad quality Bad quality product
Distance: 0.5401

Result 2
Review: Expected a better product Not good
Distance: 0.8026

Result 3
Review: Unsatisfactory - Poor Product  + Poor Customer Service I have to purchase last month 16th Oct  and with in 1 month its showing error in system in this radio, i have to complaint but already 7 days gone, no one can give the exactly response.
Distance: 0.813

Result 4
Review: Horrible waste of money , quality is very bad
Distance: 0.8148

Result 5
Review: Did not meet expectations Worst qualityPlease don't buy
Distance: 0.8335

In [63]:
print(
    "Unique products:",
    rag_df["Product_name"].nunique()
)

Unique products: 392

In [64]:
full_collection = persistent_client.get_or_create_collection(
    name="all_customer_reviews"
)

print("Currently stored:", full_collection.count())

Currently stored: 0

In [65]:
batch_size = 1000

print("Batch size:", batch_size)
print("Total reviews:", len(df))

Batch size: 1000
Total reviews: 306316

In [66]:
start = 0
end = start + batch_size

batch_df = df.iloc[start:end]

print("Batch shape:", batch_df.shape)
print("Start:", start)
print("End:", end)

Batch shape: (1000, 10)
Start: 0
End: 1000

In [67]:
batch_documents = batch_df["full_review"].astype(str).tolist()

print("Documents:", len(batch_documents))
print()
print("First document:")
print(batch_documents[0])

Documents: 1000

First document:
Simply awesome it's really worth every single penny. it works like one ton AC provided that your room has proper ventilation.  I generally keep cooler near to window so that it can pull fresh air from outside and as a result I get very cool air. one more suggestion,  please don't buy cooler which are equipped with a blower fan. Always go for the cooler equipped with metal fan like this one.  In one word, this Compton cooler is Amazing. if you find the review helpful, please thumps up. Happy summer! ????

batch_embeddings = embedding_model.encode(
    batch_documents,
    show_progress_bar=True
)

print("Embedding shape:", batch_embeddings.shape)

In [68]:
batch_embeddings = embedding_model.encode(
    batch_documents,
    show_progress_bar=True
)

print("Embedding shape:", batch_embeddings.shape)

Batches: 100%|██████████| 32/32 [00:06<00:00,  4.66it/s]

Embedding shape: (1000, 384)

In [69]:

batch_ids = [
    f"review_{i}"
    for i in range(start, end)
]

print("Number of IDs:", len(batch_ids))
print("First 3:", batch_ids[:3])
print("Last 3:", batch_ids[-3:])

Number of IDs: 1000
First 3: ['review_0', 'review_1', 'review_2']
Last 3: ['review_997', 'review_998', 'review_999']

In [70]:
batch_metadatas = []

for _, row in batch_df.iterrows():
    batch_metadatas.append({
        "product": str(row["Product_name"]),
        "rating": float(row["Rate"]),
        "sentiment": str(row["sentiment"])
    })

print("Metadata records:", len(batch_metadatas))
print()
print("First metadata:")
print(batch_metadatas[0])

Metadata records: 1000

First metadata:
{'product': 'Crompton 75 L Desert Air Cooler(White, Teal, ACGC-DAC751)', 'rating': 5.0, 'sentiment': 'Positive'}

In [71]:
full_collection.add(
    ids=batch_ids,
    documents=batch_documents,
    embeddings=batch_embeddings.tolist(),
    metadatas=batch_metadatas
)

In [72]:
print("Total records stored:", full_collection.count())

Total records stored: 1000

In [73]:
total_rows = len(df)
batch_size = 1000

for start in range(1000, total_rows, batch_size):
    end = min(start + batch_size, total_rows)

    batch_df = df.iloc[start:end]

    batch_documents = (
        batch_df["full_review"]
        .astype(str)
        .tolist()
    )

    batch_embeddings = embedding_model.encode(
        batch_documents,
        show_progress_bar=False
    )

    batch_ids = [
        f"review_{i}"
        for i in range(start, end)
    ]

    batch_metadatas = []

    for _, row in batch_df.iterrows():
        batch_metadatas.append({
            "product": str(row["Product_name"]),
            "rating": float(row["Rate"]),
            "sentiment": str(row["sentiment"])
        })

    full_collection.add(
        ids=batch_ids,
        documents=batch_documents,
        embeddings=batch_embeddings.tolist(),
        metadatas=batch_metadatas
    )

    print(
        f"Stored {end}/{total_rows} reviews"
    )

Stored 2000/306316 reviews
Stored 3000/306316 reviews
Stored 4000/306316 reviews
Stored 5000/306316 reviews
Stored 6000/306316 reviews
Stored 7000/306316 reviews
Stored 8000/306316 reviews
Stored 9000/306316 reviews
Stored 10000/306316 reviews
Stored 11000/306316 reviews
Stored 12000/306316 reviews
Stored 13000/306316 reviews
Stored 14000/306316 reviews
Stored 15000/306316 reviews
Stored 16000/306316 reviews
Stored 17000/306316 reviews
Stored 18000/306316 reviews
Stored 19000/306316 reviews
Stored 20000/306316 reviews
Stored 21000/306316 reviews
Stored 22000/306316 reviews
Stored 23000/306316 reviews
Stored 24000/306316 reviews
Stored 25000/306316 reviews
Stored 26000/306316 reviews
Stored 27000/306316 reviews
Stored 28000/306316 reviews
Stored 29000/306316 reviews
Stored 30000/306316 reviews
Stored 31000/306316 reviews
Stored 32000/306316 reviews
Stored 33000/306316 reviews
Stored 34000/306316 reviews
Stored 35000/306316 reviews
Stored 36000/306316 reviews
Stored 37000/306316 reviews
Stored 38000/306316 reviews
Stored 39000/306316 reviews
Stored 40000/306316 reviews
Stored 41000/306316 reviews
Stored 42000/306316 reviews
Stored 43000/306316 reviews
Stored 44000/306316 reviews
Stored 45000/306316 reviews
Stored 46000/306316 reviews
Stored 47000/306316 reviews
Stored 48000/306316 reviews
Stored 49000/306316 reviews
Stored 50000/306316 reviews
Stored 51000/306316 reviews
Stored 52000/306316 reviews
Stored 53000/306316 reviews
Stored 54000/306316 reviews
Stored 55000/306316 reviews
Stored 56000/306316 reviews
Stored 57000/306316 reviews
Stored 58000/306316 reviews
Stored 59000/306316 reviews
Stored 60000/306316 reviews
Stored 61000/306316 reviews
Stored 62000/306316 reviews
Stored 63000/306316 reviews
Stored 64000/306316 reviews
Stored 65000/306316 reviews
Stored 66000/306316 reviews
Stored 67000/306316 reviews
Stored 68000/306316 reviews
Stored 69000/306316 reviews
Stored 70000/306316 reviews
Stored 71000/306316 reviews
Stored 72000/306316 reviews
Stored 73000/306316 reviews
Stored 74000/306316 reviews
Stored 75000/306316 reviews
Stored 76000/306316 reviews
Stored 77000/306316 reviews
Stored 78000/306316 reviews
Stored 79000/306316 reviews
Stored 80000/306316 reviews
Stored 81000/306316 reviews
Stored 82000/306316 reviews
Stored 83000/306316 reviews
Stored 84000/306316 reviews
Stored 85000/306316 reviews
Stored 86000/306316 reviews
Stored 87000/306316 reviews
Stored 88000/306316 reviews
Stored 89000/306316 reviews
Stored 90000/306316 reviews
Stored 91000/306316 reviews
Stored 92000/306316 reviews
Stored 93000/306316 reviews
Stored 94000/306316 reviews
Stored 95000/306316 reviews
Stored 96000/306316 reviews
Stored 97000/306316 reviews
Stored 98000/306316 reviews
Stored 99000/306316 reviews
Stored 100000/306316 reviews
Stored 101000/306316 reviews
Stored 102000/306316 reviews
Stored 103000/306316 reviews
Stored 104000/306316 reviews
Stored 105000/306316 reviews
Stored 106000/306316 reviews
Stored 107000/306316 reviews
Stored 108000/306316 reviews
Stored 109000/306316 reviews
Stored 110000/306316 reviews
Stored 111000/306316 reviews
Stored 112000/306316 reviews
Stored 113000/306316 reviews
Stored 114000/306316 reviews
Stored 115000/306316 reviews
Stored 116000/306316 reviews
Stored 117000/306316 reviews
Stored 118000/306316 reviews
Stored 119000/306316 reviews
Stored 120000/306316 reviews
Stored 121000/306316 reviews
Stored 122000/306316 reviews
Stored 123000/306316 reviews
Stored 124000/306316 reviews
Stored 125000/306316 reviews
Stored 126000/306316 reviews
Stored 127000/306316 reviews
Stored 128000/306316 reviews
Stored 129000/306316 reviews
Stored 130000/306316 reviews
Stored 131000/306316 reviews
Stored 132000/306316 reviews
Stored 133000/306316 reviews
Stored 134000/306316 reviews
Stored 135000/306316 reviews
Stored 136000/306316 reviews
Stored 137000/306316 reviews
Stored 138000/306316 reviews
Stored 139000/306316 reviews
Stored 140000/306316 reviews
Stored 141000/306316 reviews
Stored 142000/306316 reviews
Stored 143000/306316 reviews
Stored 144000/306316 reviews
Stored 145000/306316 reviews
Stored 146000/306316 reviews
Stored 147000/306316 reviews
Stored 148000/306316 reviews
Stored 149000/306316 reviews
Stored 150000/306316 reviews
Stored 151000/306316 reviews
Stored 152000/306316 reviews
Stored 153000/306316 reviews
Stored 154000/306316 reviews
Stored 155000/306316 reviews
Stored 156000/306316 reviews
Stored 157000/306316 reviews
Stored 158000/306316 reviews
Stored 159000/306316 reviews
Stored 160000/306316 reviews
Stored 161000/306316 reviews
Stored 162000/306316 reviews
Stored 163000/306316 reviews
Stored 164000/306316 reviews
Stored 165000/306316 reviews
Stored 166000/306316 reviews
Stored 167000/306316 reviews
Stored 168000/306316 reviews
Stored 169000/306316 reviews
Stored 170000/306316 reviews
Stored 171000/306316 reviews
Stored 172000/306316 reviews
Stored 173000/306316 reviews
Stored 174000/306316 reviews
Stored 175000/306316 reviews
Stored 176000/306316 reviews
Stored 177000/306316 reviews
Stored 178000/306316 reviews
Stored 179000/306316 reviews
Stored 180000/306316 reviews
Stored 181000/306316 reviews
Stored 182000/306316 reviews
Stored 183000/306316 reviews
Stored 184000/306316 reviews
Stored 185000/306316 reviews
Stored 186000/306316 reviews
Stored 187000/306316 reviews
Stored 188000/306316 reviews
Stored 189000/306316 reviews
Stored 190000/306316 reviews
Stored 191000/306316 reviews
Stored 192000/306316 reviews
Stored 193000/306316 reviews
Stored 194000/306316 reviews
Stored 195000/306316 reviews
Stored 196000/306316 reviews
Stored 197000/306316 reviews
Stored 198000/306316 reviews
Stored 199000/306316 reviews
Stored 200000/306316 reviews
Stored 201000/306316 reviews
Stored 202000/306316 reviews
Stored 203000/306316 reviews
Stored 204000/306316 reviews
Stored 205000/306316 reviews
Stored 206000/306316 reviews
Stored 207000/306316 reviews
Stored 208000/306316 reviews
Stored 209000/306316 reviews
Stored 210000/306316 reviews
Stored 211000/306316 reviews
Stored 212000/306316 reviews
Stored 213000/306316 reviews
Stored 214000/306316 reviews
Stored 215000/306316 reviews
Stored 216000/306316 reviews
Stored 217000/306316 reviews
Stored 218000/306316 reviews
Stored 219000/306316 reviews
Stored 220000/306316 reviews
Stored 221000/306316 reviews
Stored 222000/306316 reviews
Stored 223000/306316 reviews
Stored 224000/306316 reviews
Stored 225000/306316 reviews
Stored 226000/306316 reviews
Stored 227000/306316 reviews
Stored 228000/306316 reviews
Stored 229000/306316 reviews
Stored 230000/306316 reviews
Stored 231000/306316 reviews
Stored 232000/306316 reviews
Stored 233000/306316 reviews
Stored 234000/306316 reviews
Stored 235000/306316 reviews
Stored 236000/306316 reviews
Stored 237000/306316 reviews
Stored 238000/306316 reviews
Stored 239000/306316 reviews
Stored 240000/306316 reviews
Stored 241000/306316 reviews
Stored 242000/306316 reviews
Stored 243000/306316 reviews
Stored 244000/306316 reviews
Stored 245000/306316 reviews
Stored 246000/306316 reviews
Stored 247000/306316 reviews
Stored 248000/306316 reviews
Stored 249000/306316 reviews
Stored 250000/306316 reviews
Stored 251000/306316 reviews
Stored 252000/306316 reviews
Stored 253000/306316 reviews
Stored 254000/306316 reviews
Stored 255000/306316 reviews
Stored 256000/306316 reviews
Stored 257000/306316 reviews
Stored 258000/306316 reviews
Stored 259000/306316 reviews
Stored 260000/306316 reviews
Stored 261000/306316 reviews
Stored 262000/306316 reviews
Stored 263000/306316 reviews
Stored 264000/306316 reviews
Stored 265000/306316 reviews
Stored 266000/306316 reviews
Stored 267000/306316 reviews
Stored 268000/306316 reviews
Stored 269000/306316 reviews
Stored 270000/306316 reviews
Stored 271000/306316 reviews
Stored 272000/306316 reviews
Stored 273000/306316 reviews
Stored 274000/306316 reviews
Stored 275000/306316 reviews
Stored 276000/306316 reviews
Stored 277000/306316 reviews
Stored 278000/306316 reviews
Stored 279000/306316 reviews
Stored 280000/306316 reviews
Stored 281000/306316 reviews
Stored 282000/306316 reviews
Stored 283000/306316 reviews
Stored 284000/306316 reviews
Stored 285000/306316 reviews
Stored 286000/306316 reviews
Stored 287000/306316 reviews
Stored 288000/306316 reviews
Stored 289000/306316 reviews
Stored 290000/306316 reviews
Stored 291000/306316 reviews
Stored 292000/306316 reviews
Stored 293000/306316 reviews
Stored 294000/306316 reviews
Stored 295000/306316 reviews
Stored 296000/306316 reviews
Stored 297000/306316 reviews
Stored 298000/306316 reviews
Stored 299000/306316 reviews
Stored 300000/306316 reviews
Stored 301000/306316 reviews
Stored 302000/306316 reviews
Stored 303000/306316 reviews
Stored 304000/306316 reviews
Stored 305000/306316 reviews
Stored 306000/306316 reviews
Stored 306316/306316 reviews

In [74]:
print("Final records:", full_collection.count())

Final records: 306316

In [75]:
query = "Air cooler is not cooling the room properly"

query_embedding = embedding_model.encode(query)

print(query_embedding.shape)

(384,)

In [76]:
full_results = full_collection.query(
    query_embeddings=[query_embedding.tolist()],
    n_results=10
)

In [77]:
for i, (review, metadata, distance) in enumerate(
    zip(
        full_results["documents"][0],
        full_results["metadatas"][0],
        full_results["distances"][0]
    ),
    start=1
):
    print(f"Result {i}")
    print("Review:", review)
    print("Product:", metadata["product"])
    print("Sentiment:", metadata["sentiment"])
    print("Rating:", metadata["rating"])
    print("Distance:", round(distance, 4))
    print("-" * 50)

Result 1
Review: Moderate This air cooler does not proper cooling than other metal body cooler,
Product: Crompton 75 L Desert Air Cooler(White, Teal, ACGC-DAC751)
Sentiment: Negative
Rating: 2.0
Distance: 0.5032
--------------------------------------------------
Result 2
Review: Moderate This air cooler does not proper cooling than other metal body cooler,
Product: Crompton 88 L Desert Air Cooler with Honeycomb Cooling Pad(White, Teal, ACGC-DAC881)
Sentiment: Negative
Rating: 2.0
Distance: 0.5032
--------------------------------------------------
Result 3
Review: Nice Entire room is not cooling even kept for day and night.avg cooling.review after use of 15 days.normal fan type.
Product: Symphony 27 L Room/Personal Air Cooler(White, Blue, Ice Cube 27)
Sentiment: Neutral
Rating: 3.0
Distance: 0.5451
--------------------------------------------------
Result 4
Review: Just okay Room is heated up even after using the cooler
Product: Crompton 75 L Desert Air Cooler(White, Teal, ACGC-DAC751)
Sentiment: Neutral
Rating: 3.0
Distance: 0.5455
--------------------------------------------------
Result 5
Review: Just okay Room is heated up even after using the cooler
Product: Crompton 88 L Desert Air Cooler with Honeycomb Cooling Pad(White, Teal, ACGC-DAC881)
Sentiment: Neutral
Rating: 3.0
Distance: 0.5455
--------------------------------------------------
Result 6
Review: Could be way better Received the product defective, not cooling. Only air coming out
Product: Crompton 75 L Desert Air Cooler(White, Teal, ACGC-DAC751)
Sentiment: Negative
Rating: 2.0
Distance: 0.5457
--------------------------------------------------
Result 7
Review: Could be way better Received the product defective, not cooling. Only air coming out
Product: Crompton 88 L Desert Air Cooler with Honeycomb Cooling Pad(White, Teal, ACGC-DAC881)
Sentiment: Negative
Rating: 2.0
Distance: 0.5457
--------------------------------------------------
Result 8
Review: Decent product Not cooling if it is inside Room
Product: Crompton 75 L Desert Air Cooler(White, Teal, ACGC-DAC751)
Sentiment: Neutral
Rating: 3.0
Distance: 0.5602
--------------------------------------------------
Result 9
Review: Decent product Not cooling if it is inside Room
Product: Crompton 88 L Desert Air Cooler with Honeycomb Cooling Pad(White, Teal, ACGC-DAC881)
Sentiment: Neutral
Rating: 3.0
Distance: 0.5602
--------------------------------------------------
Result 10
Review: Expected a better product No cooling. Just it is working as a fan. Even in a small room and for a single person, it is not giving any cool air
Product: Symphony 27 L Room/Personal Air Cooler(White, Blue, Ice Cube 27)
Sentiment: Negative
Rating: 2.0
Distance: 0.5912
--------------------------------------------------

In [78]:
retrieved_reviews = full_results["documents"][0]

context = "\n\n".join(retrieved_reviews)

print(context[:2000])

Moderate This air cooler does not proper cooling than other metal body cooler,

Moderate This air cooler does not proper cooling than other metal body cooler,

Nice Entire room is not cooling even kept for day and night.avg cooling.review after use of 15 days.normal fan type.

Just okay Room is heated up even after using the cooler

Just okay Room is heated up even after using the cooler

Could be way better Received the product defective, not cooling. Only air coming out

Could be way better Received the product defective, not cooling. Only air coming out

Decent product Not cooling if it is inside Room

Decent product Not cooling if it is inside Room

Expected a better product No cooling. Just it is working as a fan. Even in a small room and for a single person, it is not giving any cool air

In [79]:
prompt = f"""
You are a customer review analysis assistant.

Answer the user's question using only the customer reviews provided below.
Do not make claims that are not supported by the reviews.
If the reviews do not contain enough information, say that there is not enough information.

Customer Reviews:
{context}

Question:
{query}

Answer:
"""

print(prompt[:3000])

You are a customer review analysis assistant.

Answer the user's question using only the customer reviews provided below.
Do not make claims that are not supported by the reviews.
If the reviews do not contain enough information, say that there is not enough information.

Customer Reviews:
Moderate This air cooler does not proper cooling than other metal body cooler,

Moderate This air cooler does not proper cooling than other metal body cooler,

Nice Entire room is not cooling even kept for day and night.avg cooling.review after use of 15 days.normal fan type.

Just okay Room is heated up even after using the cooler

Just okay Room is heated up even after using the cooler

Could be way better Received the product defective, not cooling. Only air coming out

Could be way better Received the product defective, not cooling. Only air coming out

Decent product Not cooling if it is inside Room

Decent product Not cooling if it is inside Room

Expected a better product No cooling. Just it is working as a fan. Even in a small room and for a single person, it is not giving any cool air

Question:
Air cooler is not cooling the room properly

Answer:

In [1]:
import os

print(os.getenv("GEMINI_API_KEY") is not None)

True

In [2]:
from google import genai

client = genai.Client()

print("Gemini client created")

Gemini client created

In [3]:
response = client.models.generate_content(
    model="gemini-2.5-flash",
    contents="Explain sentiment analysis in two simple sentences."
)

print(response.text)

Sentiment analysis is the automated process of determining the emotional tone or opinion expressed in a piece of text, categorizing it as positive, negative, or neutral. It helps businesses and researchers understand public perception, track brand reputation, and analyze customer feedback at scale.

In [4]:
rag_response = client.models.generate_content(
    model="gemini-2.5-flash",
    contents=prompt
)

print(rag_response.text)

NameError: name 'prompt' is not defined

In [5]:
print("context" in globals())

False

In [6]:
from sentence_transformers import SentenceTransformer

embedding_model = SentenceTransformer(
    "sentence-transformers/all-MiniLM-L6-v2"
)

print("Embedding model loaded")

c:\Users\RUSHIKESH\Desktop\customer-review-intelligence\venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 1893.62it/s]

Embedding model loaded

In [7]:
import chromadb

persistent_client = chromadb.PersistentClient(
    path="../vector_db"
)

full_collection = persistent_client.get_collection(
    name="all_customer_reviews"
)

print("Reviews available:", full_collection.count())

Reviews available: 306316

In [8]:
query = "Air cooler is not cooling the room properly"

query_embedding = embedding_model.encode(query)

full_results = full_collection.query(
    query_embeddings=[query_embedding.tolist()],
    n_results=10
)

print("Retrieved reviews:", len(full_results["documents"][0]))

Retrieved reviews: 10

In [9]:
retrieved_reviews = full_results["documents"][0]

context = "\n\n".join(retrieved_reviews)

print(context[:1000])

Moderate This air cooler does not proper cooling than other metal body cooler,

Moderate This air cooler does not proper cooling than other metal body cooler,

Nice Entire room is not cooling even kept for day and night.avg cooling.review after use of 15 days.normal fan type.

Just okay Room is heated up even after using the cooler

Just okay Room is heated up even after using the cooler

Could be way better Received the product defective, not cooling. Only air coming out

Could be way better Received the product defective, not cooling. Only air coming out

Decent product Not cooling if it is inside Room

Decent product Not cooling if it is inside Room

Expected a better product No cooling. Just it is working as a fan. Even in a small room and for a single person, it is not giving any cool air

In [10]:
prompt = f"""
You are a customer review analysis assistant.

Answer the user's question using only the customer reviews provided below.

Do not make claims that are not supported by the reviews.
If there is not enough information in the reviews, say that there is not enough information.

Customer Reviews:
{context}

Question:
{query}

Answer:
"""

print(prompt[:1500])

You are a customer review analysis assistant.

Answer the user's question using only the customer reviews provided below.

Do not make claims that are not supported by the reviews.
If there is not enough information in the reviews, say that there is not enough information.

Customer Reviews:
Moderate This air cooler does not proper cooling than other metal body cooler,

Moderate This air cooler does not proper cooling than other metal body cooler,

Nice Entire room is not cooling even kept for day and night.avg cooling.review after use of 15 days.normal fan type.

Just okay Room is heated up even after using the cooler

Just okay Room is heated up even after using the cooler

Could be way better Received the product defective, not cooling. Only air coming out

Could be way better Received the product defective, not cooling. Only air coming out

Decent product Not cooling if it is inside Room

Decent product Not cooling if it is inside Room

Expected a better product No cooling. Just it is working as a fan. Even in a small room and for a single person, it is not giving any cool air

Question:
Air cooler is not cooling the room properly

Answer:

In [11]:
from google import genai

client = genai.Client()

In [12]:
rag_response = client.models.generate_content(
    model="gemini-2.5-flash",
    contents=prompt
)

print(rag_response.text)

Yes, according to the customer reviews, the air cooler is not cooling the room properly. Several reviews mention that the entire room is not cooling, the room is heated up even after using the cooler, or that it is not cooling at all and only works like a fan. Some even received defective units that were not cooling.

In [13]:
def ask_reviews(question):
    print("Question:", question)

In [14]:
ask_reviews(
    "What problems are customers facing with air coolers?"
)

Question: What problems are customers facing with air coolers?

In [15]:
def ask_reviews(question):

    print("Question:", question)

    query_embedding = embedding_model.encode(question)

    print("Embedding shape:", query_embedding.shape)

In [16]:
ask_reviews(
    "What problems are customers facing with air coolers?"
)

Question: What problems are customers facing with air coolers?
Embedding shape: (384,)

In [17]:
def ask_reviews(question):

    query_embedding = embedding_model.encode(question)

    results = full_collection.query(
        query_embeddings=[query_embedding.tolist()],
        n_results=5
    )

    retrieved_reviews = results["documents"][0]

    return retrieved_reviews

In [18]:
reviews = ask_reviews(
    "What problems are customers facing with air coolers?"
)

for review in reviews:
    print(review)
    print("-" * 50)

Does the job Not so good air coolerThat's it
--------------------------------------------------
Does the job Not so good air coolerThat's it
--------------------------------------------------
Hated it! Worst product. Not working after 6 month. Don't buy Crompton Air Coolers.
--------------------------------------------------
Hated it! Worst product. Not working after 6 month. Don't buy Crompton Air Coolers.
--------------------------------------------------
Worst experience ever! Cooling is not good ????????
--------------------------------------------------

In [19]:

def ask_reviews(question):

    query_embedding = embedding_model.encode(question)

    results = full_collection.query(
        query_embeddings=[query_embedding.tolist()],
        n_results=5
    )

    retrieved_reviews = results["documents"][0]

    context = "\n\n".join(retrieved_reviews)

    return context

In [20]:
context = ask_reviews(
    "What problems are customers facing with air coolers?"
)

print(context)

Does the job Not so good air coolerThat's it

Does the job Not so good air coolerThat's it

Hated it! Worst product. Not working after 6 month. Don't buy Crompton Air Coolers.

Hated it! Worst product. Not working after 6 month. Don't buy Crompton Air Coolers.

Worst experience ever! Cooling is not good ????????

In [21]:
def ask_reviews(question):

    query_embedding = embedding_model.encode(question)

    results = full_collection.query(
        query_embeddings=[query_embedding.tolist()],
        n_results=5
    )

    retrieved_reviews = results["documents"][0]

    context = "\n\n".join(retrieved_reviews)

    prompt = f"""
You are a customer review analysis assistant.

Answer the user's question using only the customer reviews provided below.

Do not make claims that are not supported by the reviews.
If the reviews do not contain enough information, say that there is not enough information.

Customer Reviews:
{context}

Question:
{question}

Answer:
"""

    return prompt

In [22]:
prompt = ask_reviews(
    "What problems are customers facing with air coolers?"
)

print(prompt[:2000])

You are a customer review analysis assistant.

Answer the user's question using only the customer reviews provided below.

Do not make claims that are not supported by the reviews.
If the reviews do not contain enough information, say that there is not enough information.

Customer Reviews:
Does the job Not so good air coolerThat's it

Does the job Not so good air coolerThat's it

Hated it! Worst product. Not working after 6 month. Don't buy Crompton Air Coolers.

Hated it! Worst product. Not working after 6 month. Don't buy Crompton Air Coolers.

Worst experience ever! Cooling is not good ????????

Question:
What problems are customers facing with air coolers?

Answer:

In [23]:
def ask_reviews(question):

    query_embedding = embedding_model.encode(question)

    results = full_collection.query(
        query_embeddings=[query_embedding.tolist()],
        n_results=5
    )

    retrieved_reviews = results["documents"][0]

    context = "\n\n".join(retrieved_reviews)

    prompt = f"""
You are a customer review analysis assistant.

Answer the user's question using only the customer reviews provided below.

Do not make claims that are not supported by the reviews.
If the reviews do not contain enough information, say that there is not enough information.

Customer Reviews:
{context}

Question:
{question}

Answer:
"""

    response = client.models.generate_content(
        model="gemini-2.5-flash",
        contents=prompt
    )

    return response.text

In [24]:
answer = ask_reviews(
    "What problems are customers facing with air coolers?"
)

print(answer)

Customers are facing the following problems with air coolers:
*   They are "not so good air cooler" in general.
*   Some units are "not working after 6 month".
*   "Cooling is not good".

In [25]:
ask_reviews("What problems are customers facing with air coolers?")

'Customers are facing the following problems with air coolers:\n*   The air cooler is "not so good" or considered the "worst product" by some.\n*   Some units are "not working after 6 months."\n*   The "cooling is not good."'

In [26]:
question = "What problems are customers facing with air coolers?"

query_embedding = embedding_model.encode(question)

negative_results = full_collection.query(
    query_embeddings=[query_embedding.tolist()],
    n_results=5,
    where={"sentiment": "Negative"}
)

for review in negative_results["documents"][0]:
    print(review)
    print("-" * 50)

Hated it! Worst product. Not working after 6 month. Don't buy Crompton Air Coolers.
--------------------------------------------------
Hated it! Worst product. Not working after 6 month. Don't buy Crompton Air Coolers.
--------------------------------------------------
Worst experience ever! Cooling is not good ????????
--------------------------------------------------
Worst experience ever! Worst air cooler
--------------------------------------------------
Terrible product Nathing to much cooling  very very bad company nathing f as St air and to much vinter
--------------------------------------------------

In [27]:
answer = ask_reviews(
    "What are the main product quality complaints from customers?"
)

print(answer)

The main product quality complaints from customers are that the product quality is not good and doesn't reach expectations. Some customers also mentioned unexpected product quality.

In [28]:
answer = ask_reviews(
    "What battery and charging problems are customers reporting?"
)

print(answer)

Customers are reporting "battery issues" and a "battery problem." They are also reporting a "charging problem."

In [29]:
question = "What battery and charging problems are customers reporting?"

query_embedding = embedding_model.encode(question)

test_results = full_collection.query(
    query_embeddings=[query_embedding.tolist()],
    n_results=10
)

for i, (review, distance) in enumerate(
    zip(
        test_results["documents"][0],
        test_results["distances"][0]
    ),
    start=1
):
    print(f"{i}. {review}")
    print("Distance:", round(distance, 4))
    print("-" * 50)

1. Decent product Battery issues
Distance: 0.5641
--------------------------------------------------
2. Terrible product battery issue
Distance: 0.6749
--------------------------------------------------
3. Horrible Battery problem
Distance: 0.6893
--------------------------------------------------
4. Horrible BATTERY PROBLEM
Distance: 0.6893
--------------------------------------------------
5. Good Charging problem
Distance: 0.6991
--------------------------------------------------
6. Not recommended at all Battery charging issue
Distance: 0.6995
--------------------------------------------------
7. Moderate Battery fault
Distance: 0.7138
--------------------------------------------------
8. Not good Charging problem
Distance: 0.743
--------------------------------------------------
9. Terrible product Charge problem
Distance: 0.7523
--------------------------------------------------
10. Just okay battery problems
Distance: 0.7541
--------------------------------------------------

In [30]:
question = """
Describe specific battery and charging issues customers experience,
such as battery life, charging behavior, battery backup, or battery performance.
"""

query_embedding = embedding_model.encode(question)

better_results = full_collection.query(
    query_embeddings=[query_embedding.tolist()],
    n_results=10
)

for i, review in enumerate(
    better_results["documents"][0],
    start=1
):
    print(f"{i}. {review}")
    print("-" * 50)

1. Decent product Battery issues
--------------------------------------------------
2. Decent product Battery consumption is fast. Charging is slow.
--------------------------------------------------
3. Bad quality Battery life is 3days only its bad
--------------------------------------------------
4. Moderate Battery fault
--------------------------------------------------
5. Wonderful I have used this laptop for one week and my observations are as below.1. It took 90 to 100 min to charge from 10% to 100%.  ( 5 times tested)2. Battery backup is approx 190 min to 210 min as per this usage => Full brightness, Hotspot in use, Only slideshow application run. (8 times tested)3. After buying this product I have registered it on the HP website and it is found the legal product.4. Keyboard is very very smooth.5. Sound quality is also good. 6. Refresh rate is also good....
--------------------------------------------------
6. Decent product Battery backup very bad
--------------------------------------------------
7. Very poor Battery backup is not good very very bad full charging 1 hours
--------------------------------------------------
8. Not recommended at all Battery charging issue
--------------------------------------------------
9. Great product Battery backup means
--------------------------------------------------
10. Great product Battery backup means
--------------------------------------------------

In [31]:
better_context = "\n\n".join(
    better_results["documents"][0]
)

better_prompt = f"""
You are a customer review analysis assistant.

Using only the customer reviews below, summarize the specific battery
and charging problems customers are reporting.

Focus on concrete issues rather than generic statements.
Do not invent information that is not present in the reviews.

Customer Reviews:
{better_context}

Answer:
"""

response = client.models.generate_content(
    model="gemini-2.5-flash",
    contents=better_prompt
)

print(response.text)

Customers are reporting the following specific battery and charging problems:

**Battery Problems:**
*   Fast battery consumption.
*   Short battery life or "very bad" battery backup, with one user explicitly stating their battery life is "3 days only."
*   One user observed a specific battery backup of approximately 190-210 minutes (around 3 hours 10 minutes to 3 hours 30 minutes) when used with full brightness, hotspot, and a slideshow application.

**Charging Problems:**
*   Slow charging.
*   One customer reported it takes 90 to 100 minutes to charge from 10% to 100%.
*   Another customer stated that a full charge takes 1 hour.

In [32]:
print(full_collection.count())

306316

In [1]:
from sentence_transformers import SentenceTransformer
import chromadb
from google import genai

embedding_model = SentenceTransformer(
    "sentence-transformers/all-MiniLM-L6-v2"
)

persistent_client = chromadb.PersistentClient(
    path="../vector_db"
)

full_collection = persistent_client.get_collection(
    name="all_customer_reviews"
)

client = genai.Client()

print("Reviews:", full_collection.count())

c:\Users\RUSHIKESH\Desktop\customer-review-intelligence\venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 2138.94it/s]

Reviews: 306316

In [2]:
query_expansion = {
    "battery": [
        "battery life",
        "battery backup",
        "battery drain",
        "battery performance",
        "charging",
        "charging speed"
    ],

    "camera": [
        "picture quality",
        "image quality",
        "photo",
        "video",
        "lens"
    ],

    "cooling": [
        "air flow",
        "cooling performance",
        "room cooling",
        "fan speed"
    ],

    "quality": [
        "build quality",
        "material",
        "durability",
        "performance"
    ]
}

print(query_expansion)

{'battery': ['battery life', 'battery backup', 'battery drain', 'battery performance', 'charging', 'charging speed'], 'camera': ['picture quality', 'image quality', 'photo', 'video', 'lens'], 'cooling': ['air flow', 'cooling performance', 'room cooling', 'fan speed'], 'quality': ['build quality', 'material', 'durability', 'performance']}

In [3]:
def expand_query(query):
    expanded_query = query.lower()

    for keyword, related_terms in query_expansion.items():
        if keyword in expanded_query:
            expanded_query += " " + " ".join(related_terms)

    return expanded_query

In [4]:
print(expand_query(
    "What battery problems are customers reporting?"
))

what battery problems are customers reporting? battery life battery backup battery drain battery performance charging charging speed

In [5]:
def ask_reviews(question):

    expanded_query = expand_query(question)

    query_embedding = embedding_model.encode(expanded_query)

    results = full_collection.query(
        query_embeddings=[query_embedding.tolist()],
        n_results=5
    )

    retrieved_reviews = results["documents"][0]

    context = "\n\n".join(retrieved_reviews)

    prompt = f"""
You are a customer review analysis assistant.

Answer the user's question using only the customer reviews below.

Customer Reviews:
{context}

Question:
{question}

Answer:
"""

    response = client.models.generate_content(
        model="gemini-2.5-flash",
        contents=prompt
    )

    return response.text

In [6]:
print(
    ask_reviews(
        "What battery problems are customers reporting?"
    )
)

Customers are reporting that the battery backup is not good, very bad, or non-existent. Specifically, they mention it's much shorter than advertised (e.g., 2 hours instead of 6 hours, or 6 hours instead of 12 hours).

In [7]:
retrieved_reviews = results["documents"][0]

NameError: name 'results' is not defined

In [8]:
def ask_reviews(question):

    expanded_query = expand_query(question)

    query_embedding = embedding_model.encode(expanded_query)

    results = full_collection.query(
        query_embeddings=[query_embedding.tolist()],
        n_results=10
    )

    retrieved_reviews = results["documents"][0]

    # Remove duplicate reviews
    retrieved_reviews = list(dict.fromkeys(retrieved_reviews))

    context = "\n\n".join(retrieved_reviews)

    prompt = f"""
You are a customer review analysis assistant.

Answer the user's question using only the customer reviews below.

Customer Reviews:
{context}

Question:
{question}

Answer:
"""

    response = client.models.generate_content(
        model="gemini-2.5-flash",
        contents=prompt
    )

    return response.text

In [9]:
print(
    ask_reviews(
        "What battery problems are customers reporting?"
    )
)

Customers are reporting that the battery backup is not good, very poor, or very bad. Many state that the actual battery life is significantly less than the advertised hours (e.g., 2 hours instead of 6, or 6 hours instead of 12). One customer also mentioned the battery percentage going up and down continuously.

In [10]:
sample = full_collection.get(
    ids=["review_0"],
    include=["metadatas"]
)

print(sample["metadatas"][0])

{'product': 'Crompton 75 L Desert Air Cooler(White, Teal, ACGC-DAC751)', 'rating': 5.0, 'sentiment': 'Positive'}

In [11]:
where={
    "product": "Crompton 75 L Desert Air Cooler(White, Teal, ACGC-DAC751)"
}

In [12]:
question = "What cooling problems are customers reporting?"

expanded_query = expand_query(question)

query_embedding = embedding_model.encode(expanded_query)

results = full_collection.query(
    query_embeddings=[query_embedding.tolist()],
    n_results=5,
    where={
        "product": "Crompton 75 L Desert Air Cooler(White, Teal, ACGC-DAC751)"
    }
)

for review in results["documents"][0]:
    print(review)
    print("-" * 50)

Bad quality Fan speed is very low in comparison to other brand coolers
--------------------------------------------------
Does the job cooling is not good.speed is well
--------------------------------------------------
Wonderful average product...cooling is not effective.....it's like a simple fan...speed is also slow even max.......
--------------------------------------------------
Great product Cooling is excellent even in large hall. Delivery of the product is really fast I got the item in 2days first time I am experiencing this fast delivery. And packing of the product not good time god there is no damage found in cooler.Con's:-1. Cooling the room is very fast.2. Air flow also good.3. Fan blades are made by metal because of this blades doesn't bend while cooler is running.4. Motor is also made by Crompton.5. Ice adding chamber also really cool.6. Coaster wheels are really ...
--------------------------------------------------
Good fan speed is Not good....expected more......not so cool.....average product......
--------------------------------------------------